name: ressuscitou
description: Ressuscitou
publish_to: 'none'
version: 3.1.0+28

## Comando para gerar o apk: flutter build apk --split-per-abi

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ###################### DEPENDÊNCIA LOCAL, MANTER ATUALIZADA MANUALMENTE ###################### #
  #webview_flutter 0.3.22+1 baixado do git https://github.com/flutter/plugins
  # Adicionado funcionalidades de pinch zoom e método canScrollVertically
  webview_flutter:
    path: ./plugins/webview_flutter
  #flutter_speed_dial: ^1.2.5 -> ajustado o layout desse plugin
  flutter_speed_dial:
    path: ./plugins/flutter_speed_dial
  # ###################### DEPENDÊNCIA LOCAL, MANTER ATUALIZADA MANUALMENTE ###################### #

  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  flutter_keyboard_size: ^0.1.2+2
  get: ^3.26.0
  shared_preferences: ^0.5.7+2
  flutter_form_builder: ^4.2.0
  audioplayers: ^0.16.1
  uuid: ^2.0.4
  path_provider: ^1.5.1
  package_info: ^0.4.1
  dio: ^3.0.9
  url_launcher: ^5.4.11
  percent_indicator: ^2.1.5
  numberpicker: ^1.2.0
  connectivity_plus: ^0.8.1
  photo_view: ^0.9.2
  wakelock: ^0.1.4+2
  share: ^0.6.4+3
  flushbar: ^1.10.4
  material_design_icons_flutter: 4.0.5655
  scrollable_positioned_list: ^0.1.7
  flutter_simple_treeview: ^3.0.2
  file_picker: ^2.1.7

dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/cantos.json
    - assets/img/
